project:
  type: website

website:
  title: "Wellington Izidoro"
  navbar:
    right:
      - text: "Sobre"
        href: about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://linkedin.com/in/wellingtonizidoro
  page-footer:
    left: "Website criado com [Quarto](https://quarto.org/), feito por mim"
    right:
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://linkedin.com/in/wellingtonizidoro
format:
  html:
    theme: sandstone
    css: styles.css

editor: visual

